aws:
  conn_id: aws_conn_id
  bucket: team-data-mock

  folders:
    raw_data:
      extracted_data: raw-data/extracted-files-data/
      names: raw-data/team-files/
      todo_data: raw-data/todo-files/

    cleaned_data:
      extracted_data: cleaned-data/cleaned_extracted_data/
      cleaned_todo: cleaned-data/cleaned_todo/

    processed_data: processed-data/

  file_patterns:
    chat: vayu
    phone: statistic_user
    quality: qs
    names: names

  required_file_types:
    - chat
    - phone
    - quality
    - names

snowflake:
  conn_id: my_snowflake_conn
  database: TEAM_MOCK

