import yaml

from pathlib import Path
from typing import Any

CONFIG_PATH = Path(__file__).parent / 'config.yaml'

def load_config() -> dict[str, Any]:

    if not CONFIG_PATH.exists():
        raise FileNotFoundError(f"Config file not found at {CONFIG_PATH}")

    with open(CONFIG_PATH, 'r') as f:
        config = yaml.safe_load(f)

    if not isinstance(config, dict):
        raise ValueError(f"Invalid configuration.File in {CONFIG_PATH} is empty")

    return config

CONFIG = load_config()

# AWS S3

AWS_CONFIG = CONFIG["aws"]
RAW_DATA_FOLDERS = AWS_CONFIG["folders"]["raw_data"]
CLEAN_DATA_FOLDERS = AWS_CONFIG["folders"]["cleaned_data"]

AWS_CONN_ID = AWS_CONFIG["conn_id"]
S3_BUCKET = AWS_CONFIG["bucket"]

S3_EXTRACTED_DATA = RAW_DATA_FOLDERS["extracted_data"]
S3_NAMES_DATA = RAW_DATA_FOLDERS["names"]
S3_TODO_DATA = RAW_DATA_FOLDERS["todo_data"]

S3_DISCOVERY_FOLDERS = (
    S3_EXTRACTED_DATA,
    S3_NAMES_DATA,
)

S3_CLEANED_EXTRACTED_DATA = CLEAN_DATA_FOLDERS["extracted_data"]
S3_CLEANED_TODO_DATA = CLEAN_DATA_FOLDERS["cleaned_todo"]

S3_PROCESSED_DATA_FOLDER = AWS_CONFIG["folders"]["processed_data"]

S3_FILE_PATTERNS = AWS_CONFIG["file_patterns"]

S3_REQUIRED_FILE_TYPES = set(
    AWS_CONFIG.get("required_file_types", [])
)

# SNOWFLAKE CONFIGS
SNOWFLAKE_CONFIG = CONFIG["snowflake"]

SNOWFLAKE_CONN_ID = SNOWFLAKE_CONFIG["conn_id"]
SNOWFLAKE_DATABASE = SNOWFLAKE_CONFIG["database"]
SNOWFLAKE_CLEANED_STAGE = SNOWFLAKE_CONFIG["stages"]["cleaned_data"]
SNOWFLAKE_PROCESSED_STAGE = SNOWFLAKE_CONFIG["stages"]["processed_data"]
SNOWFLAKE_BUSINESS_STAGE = SNOWFLAKE_CONFIG["stages"]["business_data"]
SNOWFLAKE_FILE_FORMAT = SNOWFLAKE_CONFIG["file_format"]

# SNOWFLAKE SCHEMAS

SNOWFLAKE_CLEAN_CHAT_DATA_SCHEMA = SNOWFLAKE_CONFIG["targets"]["chat_scores"]["schema"]
SNOWFLAKE_CLEAN_NAMES_SCHEMA = SNOWFLAKE_CONFIG["targets"]["names_data"]["schema"]
SNOWFLAKE_CLEAN_PHONE_DATA_SCHEMA = SNOWFLAKE_CONFIG["targets"]["phone_data_clean"]["schema"]
SNOWFLAKE_CLEAN_QS_DATA_SCHEMA = SNOWFLAKE_CONFIG["targets"]["qs_data_clean"]["schema"]

SNOWFLAKE_PRESENTATION_CHAT_SCHEMA = SNOWFLAKE_CONFIG["targets"]["chat_data"]["schema"]
SNOWFLAKE_PRESENTATION_PHONE_SCHEMA = SNOWFLAKE_CONFIG["targets"]["phone_data"]["schema"]
SNOWFLAKE_PRESENTATION_QS_SCHEMA = SNOWFLAKE_CONFIG["targets"]["qs_data"]["schema"]
SNOWFLAKE_PRESENTATION_TODO_SUMMARY_SCHEMA = SNOWFLAKE_CONFIG["targets"]["todo_summary"]["schema"]

SNOWFLAKE_BUSINESS_PROD_REPORT_SCHEMA = SNOWFLAKE_CONFIG["targets"]["prod_report"]["schema"]

# SNOWFLAKE TABLES

SNOWFLAKE_CLEAN_CHAT_DATA_TABLE = SNOWFLAKE_CONFIG["targets"]["chat_scores"]["table"]
SNOWFLAKE_CLEAN_NAMES_TABLE = SNOWFLAKE_CONFIG["targets"]["names_data"]["table"]
SNOWFLAKE_CLEAN_PHONE_DATA_TABLE = SNOWFLAKE_CONFIG["targets"]["phone_data_clean"]["table"]
SNOWFLAKE_CLEAN_QS_DATA_TABLE = SNOWFLAKE_CONFIG["targets"]["qs_data_clean"]["table"]

SNOWFLAKE_PRESENTATION_CHAT_TABLE = SNOWFLAKE_CONFIG["targets"]["chat_data"]["table"]
SNOWFLAKE_PRESENTATION_PHONE_TABLE = SNOWFLAKE_CONFIG["targets"]["phone_data"]["table"]
SNOWFLAKE_PRESENTATION_QS_TABLE = SNOWFLAKE_CONFIG["targets"]["qs_data"]["table"]
SNOWFLAKE_PRESENTATION_TODO_SUMMARY_TABLE= SNOWFLAKE_CONFIG["targets"]["todo_summary"]["table"]

SNOWFLAKE_BUSINESS_PROD_REPORT_TABLE = SNOWFLAKE_CONFIG["targets"]["prod_report"]["table"]

CLEANSED_LAYER_SCHEMAS = {
    "chat":(SNOWFLAKE_DATABASE, SNOWFLAKE_CLEAN_CHAT_DATA_SCHEMA, SNOWFLAKE_CLEAN_CHAT_DATA_TABLE),
    "names": (SNOWFLAKE_DATABASE, SNOWFLAKE_CLEAN_NAMES_SCHEMA, SNOWFLAKE_CLEAN_NAMES_TABLE),
    "phone": (SNOWFLAKE_DATABASE, SNOWFLAKE_CLEAN_PHONE_DATA_SCHEMA, SNOWFLAKE_CLEAN_PHONE_DATA_TABLE ),
    "quality": (SNOWFLAKE_DATABASE, SNOWFLAKE_CLEAN_QS_DATA_SCHEMA, SNOWFLAKE_CLEAN_QS_DATA_TABLE),
}

PRESENTATION_LAYER_SCHEMAS = {
    "chat": (SNOWFLAKE_DATABASE, SNOWFLAKE_PRESENTATION_CHAT_SCHEMA, SNOWFLAKE_PRESENTATION_CHAT_TABLE),
    "phone": (SNOWFLAKE_DATABASE, SNOWFLAKE_PRESENTATION_PHONE_SCHEMA, SNOWFLAKE_PRESENTATION_PHONE_TABLE),
    "quality": (SNOWFLAKE_DATABASE, SNOWFLAKE_PRESENTATION_QS_SCHEMA, SNOWFLAKE_PRESENTATION_QS_TABLE),
    "todo_summary": (SNOWFLAKE_DATABASE, SNOWFLAKE_PRESENTATION_TODO_SUMMARY_SCHEMA, SNOWFLAKE_PRESENTATION_TODO_SUMMARY_TABLE),
}

BUSINESS_LAYER_SCHEMAS = {
    "productivity_table": (SNOWFLAKE_DATABASE, SNOWFLAKE_BUSINESS_PROD_REPORT_SCHEMA, SNOWFLAKE_BUSINESS_PROD_REPORT_TABLE),
}