CREATE DATABASE IF NOT EXISTS TEAM_MOCK;

CREATE SCHEMA IF NOT EXISTS CLEANSED_LAYER;
CREATE SCHEMA IF NOT EXISTS STAGING_LAYER;
CREATE SCHEMA IF NOT EXISTS BUSINESS_LAYER;
CREATE SCHEMA IF NOT EXISTS PRESENTATION_LAYER;

CREATE OR REPLACE FILE FORMAT CLEANSED_LAYER.PARQUET_FORMAT
  TYPE = 'PARQUET'
  USE_LOGICAL_TYPE = TRUE;

CREATE OR REPLACE FILE FORMAT PRESENTATION_LAYER.PARQUET_FORMAT
  TYPE = 'PARQUET'
  USE_LOGICAL_TYPE = TRUE;

CREATE OR REPLACE FILE FORMAT BUSINESS_LAYER.PARQUET_FORMAT
  TYPE = 'PARQUET'
  USE_LOGICAL_TYPE = TRUE;

CREATE OR REPLACE STAGE CLEANSED_LAYER.CLEANED_DATA_STAGE
  URL = 's3://team-data-mock/cleaned-data/cleaned_extracted_data/'
  CREDENTIALS = (
    AWS_KEY_ID = ''
    AWS_SECRET_KEY = ''
  )
  FILE_FORMAT = CLEANSED_LAYER.PARQUET_FORMAT;

CREATE OR REPLACE STAGE PRESENTATION_LAYER.PROCESSED_DATA_STAGE
  URL = 's3://team-data-mock/processed-data/'
  CREDENTIALS = (
    AWS_KEY_ID = ''
    AWS_SECRET_KEY = ''
  )
  FILE_FORMAT = PRESENTATION_LAYER.PARQUET_FORMAT;

CREATE OR REPLACE STAGE BUSINESS_LAYER.PROCESSED_DATA_STAGE
  URL = 's3://team-data-mock/processed-data/'
  CREDENTIALS = (
    AWS_KEY_ID = ''
    AWS_SECRET_KEY = ''
  )
  FILE_FORMAT = BUSINESS_LAYER.PARQUET_FORMAT;

LIST @CLEANSED_LAYER.CLEANED_DATA_STAGE;
LIST @PRESENTATION_LAYER.PROCESSED_DATA_STAGE;
LIST @BUSINESS_LAYER.PROCESSED_DATA_STAGE;


CREATE TABLE IF NOT EXISTS CLEANSED_LAYER.CLEAN_CHAT_SCORES (
    RECORD_ID INTEGER,
    USER STRING
);

CREATE TABLE IF NOT EXISTS CLEANSED_LAYER.CLEAN_NAMES_DATA (
    ID INTEGER,
    NAME STRING,
    PHONE STRING,
    CHAT STRING,
    EMAIL_ADDRESS STRING,
    TODO_FILE STRING
);

CREATE TABLE IF NOT EXISTS CLEANSED_LAYER.CLEAN_PHONE_DATA (
    USER STRING,
    TOTAL_CALLS INTEGER
);

CREATE TABLE IF NOT EXISTS CLEANSED_LAYER.CLEAN_QS_DATA (
    TICKET_ID STRING,
    QUALITY_PASS STRING,
    USER STRING
);


CREATE TABLE IF NOT EXISTS PRESENTATION_LAYER.CHAT_DATA (
    USER STRING,
    TOTAL_CHATS INTEGER
);

CREATE TABLE IF NOT EXISTS PRESENTATION_LAYER.PHONE_DATA (
    USER STRING,
    TOTAL_CALLS INTEGER
);

CREATE TABLE IF NOT EXISTS PRESENTATION_LAYER.QS_DATA (
    USER STRING,
    QS_SCORE NUMERIC (10, 2)
);


CREATE TABLE IF NOT EXISTS PRESENTATION_LAYER.TODO_SUMMARY (
    USER STRING,
    EMAILS_COUNT INTEGER,
    TODOS_COUNT INTEGER
);

CREATE TABLE IF NOT EXISTS BUSINESS_LAYER.PRODUCTIVITY_REPORT (
    USER STRING,
    EMAILS_COUNT INTEGER,
    TODOS_COUNT INTEGER,
    TOTAL_CHATS INTEGER,
    TOTAL_CALLS INTEGER,
    TOTAL INTEGER,
    QS_SCORE NUMERIC (10, 2)
);

SELECT * FROM CLEANSED_LAYER.CLEAN_CHAT_SCORES;
SELECT * FROM CLEANSED_LAYER.CLEAN_NAMES_DATA;
SELECT * FROM CLEANSED_LAYER.CLEAN_PHONE_DATA;
SELECT * FROM CLEANSED_LAYER.CLEAN_QS_DATA;

SELECT * FROM PRESENTATION_LAYER.CHAT_DATA;
SELECT * FROM PRESENTATION_LAYER.PHONE_DATA;
SELECT * FROM PRESENTATION_LAYER.QS_DATA;
SELECT * FROM PRESENTATION_LAYER.TODO_SUMMARY;

SELECT * FROM BUSINESS_LAYER.PRODUCTIVITY_REPORT;


